site_name: Github Pages Lab
site_url: https://ibm.github.io/maximo-labs-test/
site_author: Jan Ekstr√∏m
site_description: "Github Pages Hands on Lab"
site_dir: ../../site/github_pages

nav:
  - Get back to Maximo Labs: ..
  - Github Pages Labs:
    - Welcome to the Github Pages Labs: index.md
    - Pre-Requisites: prereqs.md
  - Exercises:
    - 1. Setup Github Pages: gh_pages.md
    - 2. Update mkdocs.yml: mkdocs_yml.md
    - 3. Change Image Location: image_locations.md
  - About: about.md

theme: readthedocs
markdown_extensions:
  - attr_list
  - admonition